name: Core
version: ${project.version}
main: fr.iban.bukkitcore.CoreBukkitPlugin
api-version: 1.16
authors: [ Iban ]
depend: [ProtocolLib, Vault]

commands:
  serveur:
  survie:
  ressource:
  annonce:
