name: SurvivalCore
version: 1.0
api-version: 1.16
main: fr.iban.survivalcore.SurvivalCorePlugin
authors: [Iban]
description: Core du projet SpartaCube
softdepend: [dynmap]
depend: [Vault, LuckPerms, Essentials, PlaceholderAPI, Core]

commands:
  site:
  discord:
  vote:
  dynmap:
    aliases: [map]
  abbc:
  tutoriel:
    aliases: [tuto]
  stoptuto:
  boutique:
  level:
  addhomes:
  pvp:
  grades: